name: Deploy

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Firmware Version
        run: echo "#define FIRMWARE_VERSION \"${{ github.ref }}\"" > src/firmware_version.h
      - name: Read Firmware Version
        run: cat src/firmware_version.h
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
      - uses: actions/upload-artifact@master
        with:
          name: pio_build_output
          path: .pio/build

  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
     release_assets_upload_url: ${{ steps.create_release.outputs.upload_url }}

  upload_release_assets:
    runs-on: ubuntu-latest
    needs: [create_release, build]

    strategy:
      matrix:
        pio_environment: ["esp8266_d1_mini", "esp32_doit_devkit_v1"]
        asset: ["firmware.bin", "firmware.elf"]

    steps:
      - uses: actions/download-artifact@master
        with:
          name: pio_build_output
          path: .pio/build
      - run: "ls -la .pio/build"
      - run: "ls .pio/build/${{matrix.pio_environment}}"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_assets_upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: .pio/build/${{matrix.pio_environment}}/${{matrix.asset}}
          asset_name: ${{matrix.pio_environment}}_${{matrix.asset}}
          asset_content_type: application/octet-stream
